# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create required directories
      run: mkdir build
    - name: Build for Windows x64
      run: dotnet publish --os win --arch x64 --self-contained true -p:PublishSingleFile=true -p:DebugType=embedded --artifacts-path build/
    - name: Build for macOS x64
      run: dotnet publish --os osx --arch x64 --self-contained true -p:PublishSingleFile=true -p:DebugType=embedded --artifacts-path build/
    - name: Build for macOS arm64
      run: dotnet publish --os osx --arch arm64 --self-contained true -p:PublishSingleFile=true -p:DebugType=embedded --artifacts-path build/
    - name: Build for Linux x64
      run: dotnet publish --os linux --arch x64 --self-contained true -p:PublishSingleFile=true -p:DebugType=embedded --artifacts-path build/
    - name: Upload Windows x64
      uses: actions/upload-artifact@v4
      with:
        name: CIDBot-Windows-x64
        path: build/publish/CIDBot/release_win-x64/CIDBot.exe
    - name: Upload macOS x64
      uses: actions/upload-artifact@v4
      with:
        name: CIDBot-macOS-x64
        path: build/publish/CIDBot/release_osx-x64/CIDBot
    - name: Upload macOS arm64
      uses: actions/upload-artifact@v4
      with:
        name: CIDBot-macOS-arm64
        path: build/publish/CIDBot/release_osx-arm64/CIDBot
    - name: Upload Linux x64
      uses: actions/upload-artifact@v4
      with:
        name: CIDBot-Linux-x64
        path: build/publish/CIDBot/release_linux-x64/CIDBot
        
