# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create required directories
      run: mkdir build
    - name: Build for Windows x64
      run: dotnet publish --os win --arch x64 --self-contained true '-p:PublishSingleFile=true;DebugType=embedded;AssemblyName=CIDBot-Win-x64' --artifacts-path build/ 
    - name: Build for macOS x64
      run: dotnet publish --os osx --arch x64 --self-contained true '-p:PublishSingleFile=true;DebugType=embedded;AssemblyName=CIDBot-macOS-x64' --artifacts-path build/
    - name: Build for macOS arm64
      run: dotnet publish --os osx --arch arm64 --self-contained true '-p:PublishSingleFile=true;DebugType=embedded;AssemblyName=CIDBot-macOS-arm64' --artifacts-path build/
    - name: Build for Linux x64
      run: dotnet publish --os linux --arch x64 --self-contained true '-p:PublishSingleFile=true;DebugType=embedded;AssemblyName=CIDBot-Linux-x64' --artifacts-path build/
    - name: Create release
      uses: ncipollo/release-action@v1.14.0
      with: 
        artifacts: build/publish/CIDBot/release_win-x64/CIDBot-Win-x64.exe,build/publish/CIDBot/release_osx-x64/CIDBot-macOS-x64,build/publish/CIDBot/release_osx-arm64/CIDBot-macOS-arm64,build/publish/CIDBot/release_linux-x64/CIDBot-Linux-x64
        makeLatest: "true"
        tag: "${{ github.run_number }}"
        
        
